#' @title DayCent single site run
#'
#' @description This function runs DayCent for a single site.
#'
#' @param site character. Site name.
#' @param scen character. Scenario descriptor and should match the schedule file name for the experimental run.
#' @param dc_exe_in Local path to the DayCent executable.
#' @param dc_path100_in character. Local path to the 100 files folder for DayCent.
#' @param output_scen character. Name of the .in file listing which outputs should be generated by DayCent for the experimental block. Default is "basic_outfiles.in".
#' @param ... Additional arguments passed to downstream functions.
#'
#' @return The function returns a character vector with the log of the DayCent run.
#'
#' @details
#' This function uses `runDayCent` to perform a DayCent run for a single site. Results are exported
#' and saved in the same site folder. This function will run one scenario at a time.
#' The bin files are exported and saved in the site folder. Outputs listed in the outfiles.in file are exported and saved in an outputs folder within the site folder.
#'
#' @import dplyr
#'
#' @export
DayCentRunSite_single_run <- function(site, scen,
                                      dc_exe_in, dc_path100_in,
                                      output_scen = "basic_outfiles.in",...) {
  # Run equilibrium simulation if specified

  # Run scenario simulation if .sch file exists
  run <- scen
  sch_file <- paste0( site, "_", scen, ".sch")
  single_site_logic = T

  if (file.exists(sch_file)) {
    log <- runDayCent(outfiles = output_scen ,
                      site = site,
                      run = run,
                      dc_path100_in = dc_path100_in,
                      single_site_logic = single_site_logic)
    rename_and_move_output_files(run, paste0("./outputs/", run))
    print(log %>% tail(1))
    print(paste(site, run, "simulation complete."))
  } else {
    stop(paste0("Error: No '", sch_file, "' file is found. Please ensure it exists."))
  }
  return(log)
}
