#' @title DayCent site run
#'
#' @description Wraps up equilibrium, base, and experimental run blocks, and moves outputs to an output folder.
#'
#' @param site character. Site name.
#' @param scen character. Scenario descriptor and should match the schedule file name for the experimental run.
#' @param run_eq logical. Default is FALSE. If TRUE, DayCent runs the equilibrium and the base scenario.
#' @param run_base logical. Default is FALSE. If TRUE, DayCent runs the base scenario.
#' @param dc_exe_in Local path to the DayCent executable.
#' @param dc_path100_in character. Local path to the 100 files folder for DayCent.
#' @param output_base character. Name of the .in file listing which outputs should be generated by DayCent for the base block. Default is "few_outlines.in".
#' @param output_scen character. Name of the .in file listing which outputs should be generated by DayCent for the experimental block. Default is "basic_outfiles.in".
#' @param extensions character. Lists all file extensions using regex to be moved from the site to the scenario folder. Default is "\\.(out|csv)$".
#' @param ... Additional arguments passed to downstream functions.
#'
#' @return The function returns a character vector with the log of the DayCent run.
#'
#' @details
#' This function uses `runDayCent` to perform one or more DayCent run blocks (equilibrium, base, and experimental). Results for run blocks are exported
#' and saved in the site or scenario folder. This function will run one scenario at a time. If running an equilibrium block (run_eq = TRUE), a base block will also
#' be run.
#' The bin files are exported and saved in the site folder unless otherwise specified in the extensions argument.
#' Outputs listed in the outfiles.in file are exported and saved in an outputs scenario folder within the site folder.
#'
#' @importFrom utils tail
#' @importFrom stringr str_detect
#'
#' @export
DayCentRunSite <- function(site, scen, run_eq = FALSE, run_base = FALSE,
                           dc_exe_in, dc_path100_in,
                           output_base = "few_outfiles.in",
                           output_scen = "basic_outfiles.in",
                           extensions = "\\.(out|csv)$", ...) {
  # Run equilibrium simulation if specified


  run <- "eq"
  DDcentutilsLite::noBinFlag(run = run, runCheck =  run_eq)  # Check for .bin file before running

  if (run_eq) {
    run_base = T
    log <- DDcentutilsLite::runDayCent(outfiles = "no_outfiles.in",dc_exe_in = dc_exe_in,
                      site = site, run = run, dc_path100_in = dc_path100_in)
    if(stringr::str_detect(log |> utils::tail(1), "Abnormal")){
      print(log |> utils::tail(1))
      return(log)
      stop()
    }
    print(log |> utils::tail(1))
    print(paste(site, run, "simulation complete."))
  }


  run <- "base"
  DDcentutilsLite::noBinFlag(run,runCheck = run_base)  # Check for .bin file before running
  # Run base simulation if specified
  if (run_base) {
    log <- DDcentutilsLite::runDayCent(dc_exe_in = dc_exe_in,outfiles = output_base, site = site, run = run, dc_path100_in = dc_path100_in)
    if(stringr::str_detect(log |> utils::tail(1), "Abnormal")){
      print(log |> utils::tail(1))
      return(log)
      stop()
    }
    print(log |> utils::tail(1))
    print(paste(site, run, "simulation complete."))
  }

  # Run scenario simulation if .sch file exists
  run <- scen
  sch_file <- paste0("./", site, "_", scen, ".sch")
  if (file.exists(sch_file)) {
    log <- DDcentutilsLite::runDayCent(dc_exe_in = dc_exe_in,outfiles = output_scen , site = site, run = run, dc_path100_in = dc_path100_in)
    DDcentutilsLite::rename_and_move_output_files(run, paste0("./outputs/", scen), extensions = extensions)
    print(log |> tail(1))
    print(paste(site, run, "simulation complete."))
  } else {
    stop(paste0("Error: No '", sch_file, ".sch' file is found. Please ensure it exists."))
  }
  return(log)
}
