#' @title Run DayCent
#'
#' @description This function builds a command line execution and runs the DayCent model.
#'
#' @param outfiles character. Name of the .in file listing which outputs should be generated by DayCent. Default is "no_outfiles.in".
#' @param site character. Site name.
#' @param run character. Describes which DayCent block (equilibrium, base, or experimental) to run based on the schedule file name.
#' @param dc_exe_in Local path to the DayCent executable.
#' @param dc_path100_in character. Local path to the 100 files folder for DayCent.
#'
#' @return The function returns a character vector with the log of the DayCent run. The bin and output files are exported and saved in the site folder.
#'
#' @details
#' This function was built to be used in the DayCent function. The rename_and_move_output_files function moves any output file created to an outputs folder.
#'
#' @export
runDayCent <- function(outfiles = "no_outfiles.in", site, run,
                       dc_exe_in = dc_exe, dc_path100_in = dc_path100,
                       single_site_logic = FALSE, ...) {
  # Check if required input files exist
  if (!file.exists(outfiles)) {
    stop(paste0("Error:", outfiles, " file does not exist."))
  }
  if (!file.exists(dc_exe_in)) {
    stop(paste("Error: DayCent executable not found at:", dc_exe_in))
  }
  if (!file.exists(dc_path100_in)) {
    stop(paste("Error: Path to DC100 list file not found at:", dc_path100_in))
  }

  # Define the run type and extend arguments accordingly
  # single run logic, bypasses the spin up and directly runs the site.
  extendRun <- if (single_site_logic) {
    paste0("") #" --site ", single_site)
  } else if (run == "eq") {
    " -W eq_extend.100"
  } else if (run == "base") {
    " -W base_extend.100 --site eq_extend.100"
  }  else {
    " --site base_extend.100"
  }


  # Copy no_outfiles.in to suppress output during equilibrium run
  file.copy(from = outfiles, to = "outfiles.in", overwrite = TRUE)

  # Define equilibrium arguments
  eq_args <- paste0('-s ', site, '_', run, ' -N ', run, extendRun, ' -l "', dc_path100_in, '"')

  # Run the equilibrium process
  log <- system2(
    command = dc_exe_in,   # Path to the equilibrium executable
    args = eq_args,     # Arguments for the equilibrium run
    wait = TRUE,        # Wait for the process to finish
    stdout = TRUE,      # Capture standard output
    stderr = TRUE       # Capture standard error
  )

  return(log)  # Return the log output for further inspection
}
